# Generated by Django 5.1.4 on 2025-01-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='memeber',
            new_name='members',
        ),
    ]
